Add emoji support in markup with emoji short name surrounded with colons
YuriyGorvitovskiy/markdown-to-jsx pull request #2
Opened 2020-11-03 23:25 UTC by YuriyGorvitovskiy

2020-11-03 23:40 UTC, agavrilov requested changes
Can you use emoji-toolkit as dependency instead of copying emoji.json (https://github.com/joypixels/emoji-toolkit)? It will avoid a duplication of very big file

2020-11-03 23:44 UTC, agavrilov commented
@YuriyGorvitovskiy See name2emoji function in RichText.tsx in our code

2020-11-03 23:48 UTC, YuriyGorvitovskiy commented
It is not license friendly. Did somebody validate it?
https://www.joypixels.com/licenses/enterprise

2020-11-03 23:50 UTC, agavrilov commented
> 
> 
> It is not license friendly. Did somebody validate it?
> https://www.joypixels.com/licenses/enterprise

This license for images only. For the code, it is MIT: https://github.com/joypixels/emoji-toolkit/blob/master/LICENSE.md

2020-11-04 00:07 UTC, YuriyGorvitovskiy commented
Changed implementation to use emoji-toolkit

2020-11-04 00:08 UTC, agavrilov requested changes

2020-11-04 00:08 UTC, agavrilov commented on index.tsx
> +/*
No need for this code anymore

2020-11-04 00:08 UTC, agavrilov commented on tsconfig.json
> +    "emoji.json"
no emoji.json

2020-11-04 00:08 UTC, agavrilov commented on tsconfig.json
> +    "resolveJsonModule": true,
no need for this option

2020-11-04 00:13 UTC, agavrilov approved these changes

2020-11-04 00:39 UTC, merged